#!/usr/bin/dash

set -o errexit -o nounset

DIR="test/integration"
TEMPDIR="/tmp/soucc"

mkdir -p "$TEMPDIR"

fail() {
    echo "test $1 failed: $2"
    exit 1
}

echo "=== starting integration tests"

for fi in $(ls -1 "${DIR}/outputs/") ; do
    echo -n "> ${fi}... "
    bin/soucc "${DIR}/inputs/${fi}.souc" > "${TEMPDIR}/${fi}.c" || fail "$fi" "souc won't compile"
    gcc "${TEMPDIR}/${fi}.c" -o "${TEMPDIR}/${fi}" || fail "$fi" "gcc won't compile"
    "${TEMPDIR}/$fi" > "${TEMPDIR}/output" || fail "$fi" "fail during c run"
    diff --brief "${TEMPDIR}/output" "${DIR}/outputs/${fi}" || fail "$fi" "incorrect output"
    echo "OK."
done

echo "integration tests passed :^)"
