#!/usr/bin/dash

parse_succeed_dir="test/parser.d/valid"
parse_fail_dir="test/parser.d/invalid"

echo "=== testing parser... "

for fi in $(ls -t -r "$parse_succeed_dir")
do
    fullname="$parse_succeed_dir/$fi"
#     echo "test/parse/$fi"
    echo -n "${fi}... "

    if 
        bin/parser "$fullname"  >> /dev/null 2>&1
    then
        echo "OK."
        continue
    else
        echo "FAILED TEST:"
        bin/parser "$fullname"
        exit 1
    fi
done

echo "=== all tests passed. testing bad parses..."

for fi in $(ls -t -r "$parse_fail_dir")
do
    fullname="$parse_fail_dir/$fi"
    echo -n "${fi}... "

    if 
        bin/parser "$fullname"  >> /dev/null 2>&1
    then
        echo "FAILED (this program should not have been parsed):"
        bin/parser "$fullname"
        exit 1
    else
        echo "OK."
        continue
    fi
done

echo "all parser tests passed :^)"
