#!/usr/bin/dash

set -o errexit -o nounset

DIR="test/integration"
TEMPDIR="/tmp/soucc"

mkdir -p "$TEMPDIR"

fail() {
    echo "test $1 failed: $2"
    exit 1
}

for fi in $(ls -1 "${DIR}/outputs/") ; do
    echo "> testing $fi"
    bin/soucc "${DIR}/inputs/${fi}.souc" > "${TEMPDIR}/${fi}.c" || fail "$fi" "souc compile"
    gcc "${TEMPDIR}/${fi}.c" -o "${TEMPDIR}/${fi}" || fail "$fi" "gcc compile"
    "${TEMPDIR}/$fi" > "${TEMPDIR}/output" || fail "$fi" "c run"
    diff --brief "${TEMPDIR}/output" "${DIR}/outputs/${fi}" || fail "$fi" "diff"
done

echo "integration tests passed :^D"
